// Every visible label in both languages.
// { en: "English", ta: "தமிழ்" }
// Used by the t() helper. For bills we often show BOTH languages together
// (see tBoth) because the customer asked for headings in English + Tamil.

export const STRINGS = {
  // --- app / general ---
  appName: { en: 'SRK Flowers', ta: 'எஸ்.ஆர்.கே. மலர்கள்' },
  appTagline: { en: 'Billing', ta: 'பில்லிங்' },
  loading: { en: 'Loading...', ta: 'ஏற்றுகிறது...' },
  save: { en: 'Save', ta: 'சேமி' },
  cancel: { en: 'Cancel', ta: 'ரத்து' },
  delete: { en: 'Delete', ta: 'நீக்கு' },
  edit: { en: 'Edit', ta: 'திருத்து' },
  add: { en: 'Add', ta: 'சேர்' },
  search: { en: 'Search', ta: 'தேடு' },
  back: { en: 'Back', ta: 'பின்' },
  confirm: { en: 'Confirm', ta: 'உறுதி' },
  yes: { en: 'Yes', ta: 'ஆம்' },
  no: { en: 'No', ta: 'இல்லை' },
  close: { en: 'Close', ta: 'மூடு' },
  required: { en: 'Required', ta: 'தேவை' },
  none: { en: 'None', ta: 'எதுவுமில்லை' },
  all: { en: 'All', ta: 'அனைத்தும்' },

  // --- auth ---
  login: { en: 'Login', ta: 'உள்நுழை' },
  logout: { en: 'Logout', ta: 'வெளியேறு' },
  email: { en: 'Email', ta: 'மின்னஞ்சல்' },
  password: { en: 'Password', ta: 'கடவுச்சொல்' },
  loginTitle: { en: 'Sign in to continue', ta: 'தொடர உள்நுழையவும்' },
  wrongLogin: { en: 'Wrong email or password', ta: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்' },
  loggingIn: { en: 'Signing in...', ta: 'உள்நுழைகிறது...' },

  // --- navigation / sections ---
  home: { en: 'Home', ta: 'முகப்பு' },
  places: { en: 'Places', ta: 'ஊர்கள்' },
  place: { en: 'Place', ta: 'ஊர்' },
  merchants: { en: 'Merchants', ta: 'வியாபாரிகள்' },
  merchant: { en: 'Merchant', ta: 'வியாபாரி' },
  bills: { en: 'Bills', ta: 'பில்கள்' },
  bill: { en: 'Bill', ta: 'பில்' },
  billing: { en: 'Billing', ta: 'பில்லிங்' },
  received: { en: 'Received', ta: 'வந்தது' },
  selectMerchant: { en: 'Choose merchant', ta: 'வியாபாரியை தேர்வு செய்' },
  selectPlace: { en: 'Choose place', ta: 'ஊரை தேர்வு செய்' },
  manageFlowers: { en: 'Manage Flowers', ta: 'மலர்கள் நிர்வாகம்' },
  deleteBill: { en: 'Delete Bill', ta: 'பில் நீக்கு' },
  confirmDeleteBill: { en: 'Delete this whole bill?', ta: 'இந்த பில்லை முழுவதும் நீக்கவா?' },
  stock: { en: 'Stock', ta: 'சரக்கு' },
  flowers: { en: 'Flowers', ta: 'மலர்கள்' },
  flower: { en: 'Flower', ta: 'மலர்' },
  reports: { en: 'Reports', ta: 'அறிக்கைகள்' },
  settings: { en: 'Settings', ta: 'அமைப்புகள்' },
  users: { en: 'Users', ta: 'பயனர்கள்' },

  // --- bill fields (the important ones) ---
  date: { en: 'Date', ta: 'தேதி' },
  name: { en: 'Name', ta: 'பெயர்' },
  kilo: { en: 'Kilo', ta: 'கிலோ' },
  rate: { en: 'Rate', ta: 'விலை' },
  amount: { en: 'Amount', ta: 'தொகை' },
  total: { en: 'Total', ta: 'மொத்தம்' },
  totalAmount: { en: 'Total Amount', ta: 'மொத்தத் தொகை' },
  luggage: { en: 'Luggage', ta: 'லக்கேஜ்' },
  oldBalance: { en: 'Old Balance', ta: 'பழைய பாக்கி' },
  balance: { en: 'Balance', ta: 'பாக்கி' },
  grandTotal: { en: 'Grand Total', ta: 'மொத்தம்' },
  amountReceived: { en: 'Amount Received', ta: 'கொடுத்த தொகை' },
  balanceRemaining: { en: 'Balance', ta: 'மீதி பாக்கி' },
  noBalance: { en: 'No balance', ta: 'பாக்கி இல்லை' },
  advance: { en: 'Advance', ta: 'முன்பணம்' },
  commission: { en: 'Commission', ta: 'கமிஷன்' },
  commissionPercent: { en: 'Commission %', ta: 'கமிஷன் %' },
  addCommission: { en: 'Add commission?', ta: 'கமிஷன் சேர்க்கவா?' },
  defaultCommission: { en: 'Default commission %', ta: 'வழக்கமான கமிஷன் %' },

  // clean accounting model
  billNo: { en: 'Bill No', ta: 'பில் எண்' },
  previousBalance: { en: 'Previous Balance', ta: 'பழைய பாக்கி' },
  todaysBill: { en: "Today's Bill", ta: 'இன்றைய பில்' },
  totalPayable: { en: 'Total Payable', ta: 'மொத்த பாக்கி' },
  outstanding: { en: 'Outstanding', ta: 'நிலுவை பாக்கி' },
  totalBills: { en: 'Total Bills', ta: 'மொத்த பில்கள்' },
  paymentsReceived: { en: 'Payments Received', ta: 'வந்த பணம்' },
  recentTransactions: { en: 'Recent Transactions', ta: 'சமீபத்திய பரிவர்த்தனைகள்' },
  ledger: { en: 'Ledger', ta: 'கணக்கு பதிவு' },
  receivePayment: { en: 'Receive Payment', ta: 'பணம் பெறு' },
  remainingBalance: { en: 'Remaining Balance', ta: 'மீதி பாக்கி' },
  paymentMethod: { en: 'Payment Method', ta: 'பணம் முறை' },
  totalOutstanding: { en: 'Total Outstanding', ta: 'மொத்த நிலுவை' },
  billsGenerated: { en: 'Bills Generated', ta: 'பில்கள்' },
  pendingMerchants: { en: 'Pending Merchants', ta: 'நிலுவை வியாபாரிகள்' },
  paymentCollection: { en: 'Payment Collection', ta: 'வசூல் அறிக்கை' },
  dailySales: { en: 'Daily Sales', ta: 'தினசரி விற்பனை' },
  txnType: { en: 'Type', ta: 'வகை' },
  paid: { en: 'Paid', ta: 'செலுத்தியது' },
  unpaid: { en: 'Unpaid', ta: 'நிலுவை' },
  pending: { en: 'Pending', ta: 'நிலுவை' },
  quantity: { en: 'Quantity', ta: 'அளவு' },
  category: { en: 'Category', ta: 'வகை' },
  categories: { en: 'Categories', ta: 'வகைகள்' },

  // --- merchant fields ---
  phone: { en: 'Phone', ta: 'தொலைபேசி' },
  whatsapp: { en: 'WhatsApp', ta: 'வாட்ஸ்அப்' },
  mailId: { en: 'Email', ta: 'மின்னஞ்சல்' },
  notes: { en: 'Notes', ta: 'குறிப்பு' },

  // --- billing actions ---
  newBill: { en: 'New Bill', ta: 'புதிய பில்' },
  addFlower: { en: 'Add Flower', ta: 'மலர் சேர்' },
  addLine: { en: 'Add Item', ta: 'வரி சேர்' },
  removeLine: { en: 'Remove', ta: 'நீக்கு' },
  saveBill: { en: 'Save Bill', ta: 'பில் சேமி' },
  sendWhatsapp: { en: 'Send on WhatsApp', ta: 'வாட்ஸ்அப்பில் அனுப்பு' },
  downloadPdf: { en: 'Download PDF', ta: 'PDF பதிவிறக்கு' },
  downloadImage: { en: 'Download Image', ta: 'படம் பதிவிறக்கு' },
  recordPayment: { en: 'Money Received', ta: 'பணம் வந்தது' },
  todayReceived: { en: 'Received now', ta: 'இப்போது கொடுத்த தொகை' },

  // --- stock ---
  stockKg: { en: 'Stock (kg)', ta: 'சரக்கு (கிலோ)' },
  lowStock: { en: 'Low Stock', ta: 'சரக்கு குறைவு' },
  lowStockAlert: { en: 'Low stock!', ta: 'சரக்கு குறைவு!' },
  lowStockThreshold: { en: 'Low stock level', ta: 'குறைந்தபட்ச அளவு' },
  inStock: { en: 'In stock', ta: 'இருப்பில்' },
  outOfStock: { en: 'Out of stock', ta: 'சரக்கு இல்லை' },
  englishName: { en: 'English name', ta: 'ஆங்கிலப் பெயர்' },
  tamilName: { en: 'Tamil name', ta: 'தமிழ்ப் பெயர்' },

  // --- reports ---
  monthlySales: { en: 'Monthly Sales', ta: 'மாத விற்பனை' },
  totalSales: { en: 'Total Sales', ta: 'மொத்த விற்பனை' },
  pendingPayments: { en: 'Who has not paid', ta: 'பணம் கட்டாதவர்கள்' },
  thisMonth: { en: 'This Month', ta: 'இந்த மாதம்' },
  history: { en: 'History', ta: 'வரலாறு' },
  monthlyReport: { en: 'Monthly Report', ta: 'மாத அறிக்கை' },
  downloadReport: { en: 'Download Report', ta: 'அறிக்கை பதிவிறக்கு' },
  statement: { en: 'Statement', ta: 'கணக்கு அறிக்கை' },
  openingBalance: { en: 'Opening Balance', ta: 'தொடக்க பாக்கி' },
  closingBalance: { en: 'Closing Balance', ta: 'இறுதி பாக்கி' },
  totalReceived: { en: 'Total Received', ta: 'மொத்தம் வந்தது' },
  payments: { en: 'Payments', ta: 'வந்த பணம்' },

  // --- shop settings ---
  shopName: { en: 'Shop Name', ta: 'கடை பெயர்' },
  ownerName: { en: 'Proprietor', ta: 'உரிமையாளர்' },
  address: { en: 'Address', ta: 'முகவரி' },
  website: { en: 'Website', ta: 'இணையதளம்' },
  mapLink: { en: 'Map Location', ta: 'வரைபடம்' },
  footerQuote: { en: 'Footer Message', ta: 'கீழ் வாசகம்' },
  shopDetails: { en: 'Shop Details', ta: 'கடை விவரம்' },

  // --- roles / users ---
  admin: { en: 'Admin', ta: 'நிர்வாகி' },
  staff: { en: 'Staff', ta: 'பணியாளர்' },
  role: { en: 'Role', ta: 'பங்கு' },
  adminOnly: { en: 'Admin only', ta: 'நிர்வாகி மட்டும்' },

  // --- messages ---
  saved: { en: 'Saved', ta: 'சேமிக்கப்பட்டது' },
  deleted: { en: 'Deleted', ta: 'நீக்கப்பட்டது' },
  confirmDelete: { en: 'Delete this?', ta: 'இதை நீக்கவா?' },
  cannotDeleteMerchant: {
    en: 'This merchant has bills or payments and cannot be deleted.',
    ta: 'இந்த வியாபாரிக்கு பில் / பணம் பதிவுகள் உள்ளதால் நீக்க முடியாது.',
  },
  noData: { en: 'Nothing here yet', ta: 'இன்னும் எதுவும் இல்லை' },
  notConfigured: {
    en: 'App not connected to the database yet.',
    ta: 'பயன்பாடு இன்னும் தரவுத்தளத்துடன் இணைக்கப்படவில்லை.',
  },
}
